services:
  nextjs:
    build: .
    container_name: relax-dean-nextjs

  nginx:
    image: nginx:alpine
    container_name: relax-dean-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextjs
